### ISSUE TITLE
suggest edit in docs not working

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#1071]
suggest edit not working

![image](https://github.com/flexcompute/tidy3d/assets/4514346/d1336ef6-52b1-4e0f-927b-5110cbabc503)

![image](https://github.com/flexcompute/tidy3d/assets/4514346/ebd53eff-c5bb-406d-ac57-3acf2f866420)

**Comment by tylerflex** [comment]
Since we have the docs hosted at a different repo from the front end, we need to set the "source_repository" to one of these repos. it makes more sense to do the front end repo and I don't see a way to configure the "suggest edits" to point to a different link. Therefore I am suggested we just remove this button entirely. For reference
https://daobook.github.io/sphinx-book-theme/customize/source-files.html#add-a-button-to-suggest-edits
https://github.com/flexcompute-readthedocs/tidy3d-docs/pull/new/tyler/docs/remove_edit_page

**Comment by tylerflex** [comment]
@joamatab if you know of a way to configure them separately let me know, otherwise I'll merge that docs PR. 

Also, if you have an edit to suggest, feel free to comment it here and we can fix it, thanks!

**Comment by joamatab** [comment]
You can see how we do it in gdsfactory docs

**Comment by tylerflex** [comment]
Not sure I see what you mean. [This](https://github.com/gdsfactory/gdsfactory/blob/main/docs/_config.yml#L40-L47) is the config for gdsfactory docs correct?
Seems gdsfactory docs are already inside of the front end repo, so it doesn't have this problem?

**Comment by joamatab** [comment]
yes, if you configure the  baseurl: https://gdsfactory.github.io/gdsfactory/ pointing to your other repo it may still work

but having them on the same repo is for sure an option to have it working correctly

**Comment by tylerflex** [comment]
Unfortunately I tried a few things and they never worked, so I just removed this button for now until we find a fix.
