### ISSUE TITLE
to_file and from_file support for hdf5.gz

### ISSUE THREAD

**Issue by momchil-flex** [flexcompute/tidy3d#1146]
The gzip PR introduced zipping and unzipping of `hdf5` files in a few places, e.g. https://github.com/flexcompute/tidy3d/blob/bbac22ed35acd0bf67ba2c91534649ccaaa161d0/tidy3d/web/simulation_task.py#L351-L369

It probably makes more sense to just natively support `hdf5.gz` in `from_file` and `to_file`, and use these functions wherever needed.

**Comment by lucas-flexcompute** [comment]
Do we want an equivalent to `get_simulation_hdf5` for compressed data? https://github.com/flexcompute/tidy3d/blob/bbac22ed35acd0bf67ba2c91534649ccaaa161d0/tidy3d/web/simulation_task.py#L514-L516

It currently downloads and decompresses the `hdf5.gz` file. Since we're supporting compressed hdf5 directly, do we want a second function `get_simulation_hdf5_gz` or add a `decompress=True` argument to the existing one?
