### ISSUE TITLE
Mode volume calculator or integral plugin

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#1151]
In many situations users need to perform a spatial integral involving the refractive index and fields. One common example is the mode volume calculation for cavity modes. Doing it numerically requires users to manually grab various arrays and perform interpolation of the grids. Can we provide a plugin such that integrals can be calculated directly from various monitor data?

**Comment by momchilmm** [comment]
@tylerflex is already doing something like this internally in the adjoint plugin, can we have it more exposed?

**Comment by tylerflex** [comment]
what I have currently is a bit rudimentary and also specialized for my adjoint integration, but we could maybe generalize it and make it available. 

In the adjoint plugin I often have to prepare a scalar field F(r) (typically the multiplication of forward and adjoint E or D fields) and then integrate this over the surface areas (or volumes) of the geometries. How I handle this is by preparing an `xarray.DataArray` representing `F(r)` with coords `x, y, z` and then using trapezoidal integration. (basically I split each dimension into sections of equal size and then call `F.interp(**pts)` and sum the result with the differential dV/dA of each cell. 

What would be nicer, I think, is to 
1. use gaussian quadrature, which should be able to have a better accuracy with fewer points (although it turns out the number of points isn't as much of the speed bottleneck as is the number of `.interp()` calls with many structures).
2. wrap this gaussian quadrature inside of the `td.DataArray` as perhaps a method like `DataArray.integrate(bounds: Bound, resolution: Tuple[float, float, float]).

Would this work for the field integration? eg. mode volume? or does that require an integration that takes the x,y,z components of the fields into account in a more specific way?

Also, note that this would only really handle integration over rectangular surfaces / volumes. For more general eg slanted polyslab, cylinder, sphere, or poyslab faces, we'd probably need to move this method into `Geometry`, which becomes potentially more messy?

**Comment by tylerflex** [comment]
@tomflexcompute perhaps the easiest approach is to use `xarray.DataArray.integrate`. the documentation is [here](https://docs.xarray.dev/en/stable/generated/xarray.DataArray.integrate.html).  This does the interpolation and weighting behind the scenes and users can specify one or more dimensions to integrate over. 

For a mode volume kind of calculation, they might want to use 

```py
intensity = sim_data.get_intensity(monitor_name)
```
 and then depending on how the user wants to calculate mode volume, they can perform the integration like
```py
intensity.integrate()
```py
for example, something like
```py
mode_volume = intensity.integrate() / intensity.max()
```
```

**Comment by tylerflex** [comment]
@tomflexcompute seems like this was working fine in the nonlinear notebook, maybe we can close this issue?

**Comment by tomflexcompute** [comment]
> @tomflexcompute seems like this was working fine in the nonlinear notebook, maybe we can close this issue?

Sounds good. Thanks.
