### ISSUE TITLE
Add warning for cases taking less than 33% of the time steps when reaching auto shutoff

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#1161]
Since we charge a minimum of 1/3 of the estimated maximum and many users don't seem to know about it, should we add a warning if a task reaches auto shutoff but it took less than 1/3 of the time steps? Also when users use estimate_cost(), a message about we are charging a minimum of 1/3 of the estimated cost can be helpful.

**Comment by momchil-flex** [comment]
Note that this has now been changed to 1/10 of the cost.

**Comment by tylerflex** [comment]
@momchil-flex maybe you can handle it? You might know how to word this the best. Basically if the shutoff time < run_time * 10 we tell them that we're still charging 1/10 of the cost for the specified run_time as a minimum?

**Comment by tylerflex** [comment]
could throw a field in the task_info, maybe, to indicate if the minimum charge was triggered.

**Comment by momchil-flex** [comment]
Ok, so I was working on this but one problem is that the simulation hits `success` status a bit before the cost is computed and applied. So we can't check whether minimum charge was hit or not immediately on `web.load` during the `web.run`, as that information may not yet be available (basically it's applied after the full pipeline is done, including denormalizer, while we don't wait for denormalizer to finish the job from python).

I could do the following:
- Add a message in "estimate_cost" saying that there's a minimum cost (however without printing an explicit %-age, because this may change in the future).
- Add a warning in "real_cost" if that minimum cost was hit.

Users won't see the warning in a `web.run` though. Does that still sounds good?

**Comment by tomflexcompute** [comment]
> Ok, so I was working on this but one problem is that the simulation hits `success` status a bit before the cost is computed and applied. So we can't check whether minimum charge was hit or not immediately on `web.load` during the `web.run`, as that information may not yet be available (basically it's applied after the full pipeline is done, including denormalizer, while we don't wait for denormalizer to finish the job from python).
> 
> I could do the following:
> 
> * Add a message in "estimate_cost" saying that there's a minimum cost (however without printing an explicit %-age, because this may change in the future).
> * Add a warning in "real_cost" if that minimum cost was hit.
> 
> Users won't see the warning in a `web.run` though. Does that still sounds good?

Thanks for looking into it. I agree that it's probably the best approach for now.

**Comment by momchil-flex** [comment]
Fixed in #1207
