### ISSUE TITLE
Support dispersive materials in adjoint plugin

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#1226]
This is currently blocking things like optimizing plasmonic devices, which require using dispersive models to simulate in tidy3d.

**Comment by tylerflex** [comment]
A few things that could be implemented:
1. Jax-compatible dispersive medium [with no differentiable fields for now] but can be used for shape optimization when only the geometry is being modified.
2. Support multiple frequency points in the `JaxCustomMedium` and handle it through multi-frequency adjoint

**Comment by momchil-flex** [comment]
Hmm I don't think point 2. works directly. In the simulations, you can't provide a CustomMedium with a frequency-dependent permittivity. You need to use a `CustomDispersiveMedium` instead.

I think conceptually the way topology optimization for dispersive media may work is if we switch to a design variable that interpolates between two materials (e.g. background and some dispersive one), rather than between two fixed permittivity values. Then it should be possible to compute dJ/deps at every frequency in the usual way, and backprop through the interpolation (at every frequency, eps(f) = x * eps1(f) + (1-x) eps2(f), regardless if the materials are dispersive or not). But yeah basically instead of working with a `CustomDispersiveMedium` directly, which seems complicated, we should just work with something like a `DesignRegion(medium1, medium2, design_variable)` kinda thing, and optimize `design_variable`. This is something that we may want to have as a main tidy3d component too.

**Comment by tylerflex** [comment]
Yea that all makes sense. I'll focus on supporting non differential custom medium with differentiable geometries for now

**Comment by tylerflex** [comment]
Fixed by #1281
