### ISSUE TITLE
Add mode information in ModeMonitorData

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#1274]
Current mode monitor result only stores the effective indices and group indices of the modes. Since we have added polarization fractions and mode area information in the mode solver result, one user is wondering if we can add the same info to the mode monitor result as well for easier mode sorting.

**Comment by lucas-flexcompute** [comment]
One thing we have to consider is that polarization fraction and mode area are quantities calculated locally based on the available field distributions in `ModeSolverData` (because it derives from `ElectromagneticFieldData`). `ModeData` does not include the mode fields, so it's not possible to do the same thing. I see alternatives if we really want to implement this feature:

1. Calculate on the backend and add it directly to the results. This will increase our post-processing calculations for every mode monitor, which I'm not sure is a good idea.
2. Return the modal field information for `ModeMonitor`. If we go this route, it seems to me that `ModeMonitor` and `ModeSolverMonitor` could be merged, but I haven't checked any implementation details and differences between them. @momchil-flex would probably be the first person to chime in here, I guess. This is the solution I'd prefer, as it would decrease our API complexity in the end.

**Comment by momchil-flex** [comment]
> One thing we have to consider is that polarization fraction and mode area are quantities calculated locally based on the available field distributions in `ModeSolverData` (because it derives from `ElectromagneticFieldData`). `ModeData` does not include the mode fields, so it's not possible to do the same thing. I see 2 alternatives if we really want to implement this feature:
> 
> 1. Calculate on the backend and add it directly to the results. This will increase our post-processing calculations for every mode monitor, which I'm not sure is a good idea.

I would think this would never be comparable to the dominating computation time (computing the modes, and also other postprocessing that we already do anyway, like colocating, normalizing, and reordering), but do you have a particular worry in mind?

> 2. Return the modal field information for `ModeMonitor`. If we go this route, it seems to me that `ModeMonitor` and `ModeSolverMonitor` could be merged, but I haven't checked any implementation details and differences between them. @momchil-flex would probably be the first person to chime in here, I guess. This is the solution I'd prefer, as it would decrease our API complexity in the end.

So, very early on we had a `ModeMonitor` that could optionally store fields. Then when doing the first major refactor (introducing pydantic models, etc), we wanted to have things work in a more atomic way (e.g. there's a Monitor <-> MonitorData relationship that does not depend on the toggles of the Monitor), which led to introducing `ModeMonitor` and `ModeSolverMonitor` as separate entities. However in this particular case questions have been recurrently raised as to whether it should be rethought. I guess conceptually, within the new thinking, instead of us trying to cram things into the ModeMonitor data, a user should just place both a ModeMonitor and a ModeSolverMonitor if they are curious not just about the amplitudes, but also about the modes. In practice however this means unnecessary work since identical modes will be computed twice. Which leads one to think about fancier schemes where we have a away to filter "unique" mode solves, and distribute the data appropriately. But at this point having a single ModeMonitor with a `store_fields` kind of toggle starts becoming attractive again...

@tylerflex ?

**Comment by tylerflex** [comment]
Can we keep the current relationship between Monitor and MonitorData, but maybe package the derived mode information in a single object (ModeInfo?) that can be easily added to either Modedata or ModeSolverData?

**Comment by tylerflex** [comment]
I'm not generally opposed to combining all mode-related data in a single ModeData object, but it just means more changes and backwards compatibility stuff. In general, probably we should relax the atomic `XMonitor -> XData` relationship and can maybe more generally just define a mapping (function?) between `XMonitor` and its corresponding `XData`. I might need to do something similar in adjoint much later on.

**Comment by lucas-flexcompute** [comment]
Regarding backwards compatibility, we can leave `ModeSolverMonitor` and `ModeSolverData` as they are (maybe add a deprecation warning) and just add their functionality to `ModeMonitor` and `ModeData`. The new fields can be marked optional for now, so that old datasets can still be loaded from files.

Maybe this has been discussed before, but one thing that might make sense to facilitate backwards compatibility in general would be to have update tools on our frontend when loading files from previous versions. It's only a matter of storing version information in our base class.

**Comment by momchil-flex** [comment]
> Regarding backwards compatibility, we can leave `ModeSolverMonitor` and `ModeSolverData` as they are (maybe add a deprecation warning) and just add their functionality to `ModeMonitor` and `ModeData`. The new fields can be marked optional for now, so that old datasets can still be loaded from files.

I think that could be good yeah.

> Maybe this has been discussed before, but one thing that might make sense to facilitate backwards compatibility in general would be to have update tools on our frontend when loading files from previous versions. It's only a matter of storing version information in our base class.

We already do this for `Simulation`. We just haven't introduced the same for `SimulationData`. But, it could be good to have yeah to make compatibility really tight. So far we've just been trying not to modify the SimulationData schema in a breaking way.

**Comment by lucas-flexcompute** [comment]
Yes, to be honest I haven't started on this because of the work on PhotoForge releases. I'll try to work on this in the next couple of weeks to see how it goes, but 2.6 is probably fine.

**Comment by tylerflex** [comment]
can this be closed?
