### ISSUE TITLE
Get estimated compute as a web service.

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#132]
We should also have a web. function for estimating the compute / EM units of a simulation in the release

**Comment by joamatab** [comment]
how can we get a back of the envelope estimate of the simulation time?

**Comment by momchil-flex** [comment]
So one thing to understand about Tidy3D is that we do adaptive resource allocation, and the compute time is not a linear function of your simulation compute complexity. Smaller sims may run on fewer resources, etc. What you can currently get is an estimate of the credit cost of the simulation if you upload it without running, and have a look at the task page on client.simulation.cloud. This particular issue points out that we should have a better way to get this credit estimate directly from the python web api.

I don't really want to give a rule of thumb conversion between credits and simulation time, because credits reflect "resource time" rather than wall time, and any estimate I give now may be inaccurate and may also get even more inaccurate in the future as our resources and allocation strategies change.

That said, in the old tidy3d version we had a progress bar that shows the % done when a simulation is running. We have another issue where we've noted to bring this back here, and we'll have it for our upcoming Feb. 28 release. https://github.com/flexcompute/tidy3d/issues/140
