### ISSUE TITLE
Support anisotropic materials (including Lithium Niobate) in material library.

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#1413]
Not sure who is best to assign here

**Comment by weiliangjin2021** [comment]
I can implement the feature in material library, and maybe @tomflexcompute provides the parameter data for Lithium Niobate?

**Comment by tomflexcompute** [comment]
> I can implement the feature in material library, and maybe @tomflexcompute provides the parameter data for Lithium Niobate?

Thanks Weiliang. This [data](https://refractiveindex.info/?shelf=main&book=LiNbO3&page=Zelmon-o) seems to be quite popular among users.

**Comment by weiliangjin2021** [comment]
I guess to support anisotropic medium in material library, we'll need to adopt the approach in `parametric_materials.py`. We can support uniaxial medium in material library for now, and ask the users to define optical axis to initialize the medium. What do you think?

**Comment by tylerflex** [comment]
I think that sounds good.

**Comment by weiliangjin2021** [comment]
As I start to implement this feature, I find it hard to adopt it to our current material_library or parametric_materials:
- For uniaxial medium, material library will provide the material models for ordinary and extraordinary components. Then users set the optical axis. Finally AnistropicMedium is generated.
- This certainly needs parametric approach. But uniaxial medium has both private fields set through material libray, and the parametric field "optical_axis" set by user. Since we seem to avoid using private variables, I have been trying to think of an approach to work around it, e.g. using two classes, etc., but none is satisfactory.
- The easiest approach I have in mind now is to override the `medium` property with a method that takes `optical_axis`. @tylerflex any suggestions?

**Comment by tylerflex** [comment]
Hm, maybe @caseyflex has some thoughts? It's been a while since I worked with the material library. My thought was that (following the idea of `Graphene`) we would put the `optical_axis` in the pd.Field? but then is the issue that the user might need to select or 0, 1, 2?  I think exposing `optical_axis` in `medium()` could work.

**Comment by weiliangjin2021** [comment]
> We could introduce a new UniaxialMedium class with ordinary and extraordinary components as well as an optical_axis field? Maybe we don't need it to be parametric like graphene... There, the parameters actually generate different material models, whereas the optical_axis just tells us how the material model maps into Cartesian space. The UniaxialMedium could be internally converted to AnisotropicMedium.

The issue with that is we cannot include optical_axis in material_library. It should be defined by the user to generate appropriate anisotropoic medium.

**Comment by caseyflex** [comment]
> > We could introduce a new UniaxialMedium class with ordinary and extraordinary components as well as an optical_axis field? Maybe we don't need it to be parametric like graphene... There, the parameters actually generate different material models, whereas the optical_axis just tells us how the material model maps into Cartesian space. The UniaxialMedium could be internally converted to AnisotropicMedium.
> 
> The issue with that is we cannot include optical_axis in material_library. It should be defined by the user to generate appropriate anisotropoic medium.

In that case, I'd be in favor of overriding the `medium()` method to accept optical_axis as a parameter.
