### ISSUE TITLE
Structures in absorber trigers a warning about PML

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#1696]
When there is a structure completely inside the absorber boundary, it triggers a warning 

_WARNING: A bound of Simulation.structures[94] was
                               detected as being within the simulation PML. We  
                               recommend extending structures to infinity or    
                               completely outside of the simulation PML to avoid
                               unexpected effects when the structures are not   
                               translationally invariant within the PML._       

This seems to be related to the `pml_thicknesses` [here](https://github.com/flexcompute/tidy3d/blob/3ee34904eb6687a86a5fb3f4ed6d3295c228cd83/tidy3d/components/simulation.py#L2583) actually includes not just PML but absorber as well. Therefore `_validate_no_structures_pml` returns a warning for structures in absorber too.

**Comment by momchil-flex** [comment]
I am wondering if we should change the message instead of completely removing the warning for Absorbers. Yes, absorbers may not diverge, but I feel like this could still be indicative of an unintended setup in some cases, e.g. this can create extra reflections if the users just didn't realize that they didn't extend their structures through. What do you think?

**Comment by tomflexcompute** [comment]
Yeah that sounds good. As long as we can eliminate the confusion from the warning it should be fine.

**Comment by momchil-flex** [comment]
Seems like this was fixed, not sure in which PR exactly but now there's a `if not isinstance(bound_edge, Absorber)` check.
