### ISSUE TITLE
EME Monitor Validation

### ISSUE THREAD

**Issue by alec-flexcompute** [flexcompute/tidy3d#1732]
**Is your feature request related to a problem? Please describe.**
If a monitor is located at the boundary of an EME simulation, the simulation will run without an error and crash.

**Describe the solution you'd like**
Add a validator checking if a monitor is at the boundary of an EME simulation. Attached is an example notebook where this occurs.
[EME_validation.ipynb.zip](https://github.com/user-attachments/files/15519481/EME_validation.ipynb.zip)

**Comment by momchil-flex** [comment]
I was just about to do this also for regular simulations, so let me take this and I'll test with your EME example too.

**Comment by caseyflex** [comment]
> I was just about to do this also for regular simulations, so let me take this and I'll test with your EME example too.

Thanks. Yeah this is an issue with regular simulations too, not just EME. And I wasn't sure if we wanted to just validate to prevent this, or actually support this use case of monitors aligned exactly with simulation boundary.

**Comment by momchil-flex** [comment]
Good question. I was thinking of validating it out. In regular simulations it's a bit annoying. Basically we need a pixel on each side of the monitor to be able to interpolate fields. This works if the monitor is very close to the boundary, but on the simulation domain side. But if it happens to be seen as on the other side (due to numerical precision if they are exactly the same), we run into problems. It can be fixed internally but I really don't like touching that part of the code.

The user will still be able to put the monitor very close to the boundary... just not right on it.

**Comment by momchil-flex** [comment]
Fixed by #1733 (except for ModeSolverMonitors apparently, which @caseyflex pointed out can still be problematic if anywhere within the last pixel... leaving for the future).
