### ISSUE TITLE
Reduce the mode solver simulation time for multiple frequency points

### ISSUE THREAD

**Issue by e-g-melo** [flexcompute/tidy3d#1763]
## Current
Currently, the mode solver simulation time increases very fast with the number of frequency points. In this [task](https://tidy3d.simulation.cloud/workbench?taskId=pa-03a25af4-26ab-47c2-9d44-82a350493748), I varied the number of frequency points from 1 to 100, and including more than 10 points resulted in significantly longer simulation times, despite some variability in the simulation time from run to run.

![image](https://github.com/flexcompute/tidy3d/assets/125516370/1818e6dd-e15f-40bc-896b-8c6c8d1531cf)

According to this chart, the time spent in the solver significantly contributes to the total simulation time.

![image](https://github.com/flexcompute/tidy3d/assets/125516370/d8333cde-1f57-44ee-b2da-2ea5e26b4f64)

## Requirement
We should decrease the simulation time for such a case as it is likely to occur when users work on dispersion engineering or similar applications. This can become even more crucial if the user needs to run a batch of mode tasks.

Ideally, the simulation time for tasks with 100 or more frequency points should be only slightly longer than that for tasks with 10 or fewer points.

## Priority
I suggest giving high priority to this ticket because we've made significant efforts to reduce the total mode solver simulation time. Therefore, we need to address the larger number of frequency points as well.

**Comment by weiliangjin2021** [comment]
Thanks @e-g-melo. This actually solvers for 3 times as many frequencies in the backend because `group_index` is not None. E.g. when number of points is 100, it in fact solves for 300 frequency points.

The sudden jump in simulation is because we switch eigensolver from scipy to a parallel solver when the number of frequencies increases. In my test, when number of points is 100 (solving for 300 frequencies), the parallel solver (which actually is not parallel here) takes around 65s, while scipy solver takes 25s.

So I guess one options is to revise eigensolver choices to weigh the number of grids more @dbochkov-flexcompute ? The other option is to see anything we can do on the solver side (e.g. not use MPI when it's not running in parallel).

**Comment by dbochkov-flexcompute** [comment]
> In my test, when number of points is 100 (solving for 300 frequencies), the parallel solver (which actually is not parallel here) takes around 65s, while scipy solver takes 25s.

was it locally or on servers?

**Comment by weiliangjin2021** [comment]
> > In my test, when number of points is 100 (solving for 300 frequencies), the parallel solver (which actually is not parallel here) takes around 65s, while scipy solver takes 25s.
> 
> was it locally or on servers?

On servers (cell)
