### ISSUE TITLE
TE/TM polarization fraction sorted by neff

### ISSUE THREAD

**Issue by Matteo-Menotti** [flexcompute/tidy3d#298]
**Is your feature request related to a problem? Please describe.**
The new feature for sorting by TE/TM polarization fraction recently released is a great addition, but it would be more powerful if the user could _select_ the polarization to inject/monitor and the modes would be still ordered by decreasing effective index. The issue is that non-physical modes may have higher polarization fractions and be reported first.

**Describe the solution you'd like**
- The user selects the require polarization as either TE or TM (of course keeping in mind that the polarization fraction is not a rigorous figure of merit and works best only for low-confinement systems).
- The solver isolates the modes having >(<)0.5 polarization fraction as TE(TM)
- The solver sorts the modes with the selected polarization by decreasing effective index

**Describe alternatives you've considered**
Different configurations of the boundary conditions can help suppress spurious modes, but it's not trivial to make sure they won't appear, and in any case there is no control on their polarization fraction.
Alternatively, the user could sort by polarization locally to skim the non-physical modes, but it defies the purpose of the server-side mode sorting.

**Additional context**
An example of sorting by TE, reporting non-physical modes first (with lower effective index) and the physical modes last (with higher effective index):
![image](https://user-images.githubusercontent.com/43765270/162778328-ccb3a03f-b68c-41cb-b99e-5a335a84aa1b.png)
![image](https://user-images.githubusercontent.com/43765270/162778436-39fe6253-9bff-4e71-88d1-2b5cd48d1456.png)

**Comment by momchil-flex** [comment]
Thanks for the thorough description. I completely agree with the change, the one thing stopping us from implementing it so far (apart from our bandwidth...) is that I wasn't sure how to handle the case in which you filter the modes, and then there aren't enough modes to select the source `mode_index` from. We cannot validate that in advance, and we don't want to just error out, because that task would take up some resources on our server and eventually error out, which is something we don't charge the customer and we don't want to happen (we assume an error is something that's our fault and that we want to avoid).

What I'm thinking right now is this: we can filter the modes with the selected polarization fraction >= 0.5, but then if the `mode_index` is larger than the number of remaining modes, we revert the filtering. Does that sound good?

I'm also thinking of completely removing the `sort_by` field and replace it with `filter`, so it will be an API change - but I don't think the `sort_by` the way is ever going to be useful.

**Comment by Matteo-Menotti** [comment]
Thank you Momchil for your explanation. I understand that a failed simulation with a simple error reporting is not a good solution from the resource allocation (and cost) perspective.

I like the idea of trying to do what the user requests and in case that's impossible fall back to a safe scenario so the simulation will run. Would it be possible to have an intermediate solution, such that we:
1) divide modes in TE/TM according to polarization fraction and sort by decreasing neff
2) If the requested mode is not present pick the highest mode order (lowest neff) found with the requested polarization
3) If not found either (meaning the system does not even support the fundamental mode) we revert to filtering 

Ideally, a warning in the log file mentioning that the requested mode was nonexistent would be fantastic to have too, so the user is informed about what happened on the server side and can adjust the request in the next simulations.

>I'm also thinking of completely removing the sort_by field and replace it with filter, so it will be an API change - but I don't think the sort_by the way is ever going to be useful.

I tend to agree (at least for our use-case). I guess the only scenario that comes to mind where `sort_by=largest_neff` can be useful is if one imposes symmetric/antisymmetric conditions on the cell, and the waveguide is centered too. But apart from this, `filter`ing seems like a more effective approach. If that implies some changes in the API, it's not a problem for us.

Thank you!
