### ISSUE TITLE
Ways to save and load Smatrix scan (store internal batch information?)

### ISSUE THREAD

**Issue by momchil-flex** [flexcompute/tidy3d#373]
If I run an S-matrix scan, I would expect to have access to the batch that is used under the hood. Maybe I messed something up and want to batch delete, or who knows what else. The current workflow in the S-matrix plugin seems to be that you have to call `solve`, and wait for it to finish - that is the only way that you can get the results. If you want to interrupt the run monitoring and get back to it when it's done, it's not possible. Neither is it possible to store things and load them tomorrow, as far as I understand. Currently ComponentModeler has a load method but I actually don't see when it could possibly be used.

We probably want to store `batch` in `self.batch` - is there any downside to that? So I can for example do `modeler.batch.delete()` if I decide to cancel the run. Then we can also use the `Batch` saving and loading methods, and wrap them in methods of `ComponentModeler`.

**Comment by tylerflex** [comment]
Yea I agree we should store `batch` instead of `batch_data`.  I had it that way originally but changed it, now I don't remember why, but it does make more sense.  The component modeler should essentially be a wrapper that allows you to construct a `Batch` and post process it into an S-matrix.  The batch handling (load, delete, etc) should just use `modeler.batch` like you said.  Not sure how to handle computing just one column or row, though.
