### ISSUE TITLE
Test Coverage: Updater

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#526]
The updater has a good chunk of untested bits.
I suggest we either add some more coverage. If we're performing a major release soon, are we removing the updater? if so, probably no big need to test it more.

**Comment by momchil-flex** [comment]
So I just ran this and I get 90% coverage on the updater.. which seems pretty good? And some of the things that are not covered are very pedantic... For example, this was just added because some linter was complaining?

![image](https://user-images.githubusercontent.com/92756559/193352295-7c710aad-6466-4f18-bbea-0c1661272f87.png)

And these parts of the version class were added for completeness but in principle aren't needed

![image](https://user-images.githubusercontent.com/92756559/193352761-d100b465-07fb-4e44-b46e-296a447454a0.png)

I mean I generally understand the sentiment of having everything tested. I probably just need to get over my initial aversion to devoting time to something like this given that there are a lot of other tasks that seem higher priority/impact.

**Comment by tylerflex** [comment]
yea, these seem not very important. I actually didnt check which bits of the updater were not covered by the tests before creating these issues. We can leave them out, although probably just takes a minute or two to write them.

**Comment by tylerflex** [comment]
Fair enough. Actually i didn’t know which specific lines weren’t tested
because i didn’t know about the html output until after doing all my
testing. These lines aren’t so important compared to the actual updater
tests we have which are quite good and important.  I think it’s probably
fine to leave these lines untested but also would be pretty simple to just
make a quick test that creates and updater and does some equality checking.
