### ISSUE TITLE
`GridSpec.from_grid()` convenience method?

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#580]
Say I have just created a `Simulation`, "`sim`" and I want to try to use the exact same `Grid` on a different simulation.

What would be great is if one could use a `@classmethod` constructor to set the `GridSpec` using an existing `Grid`, like

```py
sim2 = td.Simulation(
    ...,
    grid_spec=td.GridSpec.from_grid(grid=sim.grid),
    ...,
)
```

A few questions:
1. Do you see this being useful as a feature? or foresee any caveats? 
2. What would be the way to implement this correctly, assuming using [`CustomGrid`](https://docs.flexcompute.com/projects/tidy3d/en/latest/_autosummary/tidy3d.CustomGrid.html?highlight=CustomGrid#tidy3d.CustomGrid)?

**Comment by momchil-flex** [comment]
> 1. Do you see this being useful as a feature? or foresee any caveats?

I guess we might as well support it, I can see how it could be useful in some cases for advanced users. One caveat is that the two simulations should have the same center and size for this to work well, otherwise you have to think about exactly what would happen.

> 2. What would be the way to implement this correctly, assuming using [`CustomGrid`](https://docs.flexcompute.com/projects/tidy3d/en/latest/_autosummary/tidy3d.CustomGrid.html?highlight=CustomGrid#tidy3d.CustomGrid)?

I think assuming the two simulations have the same size and center, it should be as simple as e.g.
```
grid_x = td.CustomGrid(dl=sim1.grid.sizes.x)
sim2 = td.Simulation(
    ...
    grid_spec=td.GridSpec(grid_x=grid_x, ...)
)
```

Considering that this can be tricky in the case of different simulation centers, I'm not sure if we should support it natively, what do you think?

**Comment by tylerflex** [comment]
yea, maybe we should just not support it given this constraint.
