### ISSUE TITLE
Switch all internal gdspy use to gdstk

### ISSUE THREAD

**Issue by momchil-flex** [flexcompute/tidy3d#603]
Apart from improved performance, we've had Windows users have problems installing `gdspy`. As far as I understand, `gdstk` should be better even in that respect. No reason not to switch!

**Comment by tylerflex** [comment]
Thanks for the heads up @ianwilliamson

**Comment by joamatab** [comment]
yes, gdstk has some segmentation faults that would be great to fix
overall gdstk is much faster than gdspy and easier to install because we built the gdstk wheels for windows, linux and MacOs. gdspy is hard to install without conda.


https://github.com/flexcompute/tidy3d/pull/613

**Comment by heitzmann** [comment]
Hi all, gsdtk 0.9.35 was released with fixes to the known segfault issues. The main issue was that the gdstk types were not properly configured to be used as base classes for other python classes (they were calling their deallocator directly instead of the subtype's). There was also an issue with partially initialized instances that could segfault after an exception was raised.

**Comment by tylerflex** [comment]
Looks like we can close this.
