### ISSUE TITLE
grating coupler simulations

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#627]
Grating couplers simulations don't match simulations in meep and Lumerical

https://gdsfactory.github.io/gdsfactory/notebooks/plugins/tidy3d/00_tidy3d.html#get_simulation_grating_coupler

https://gdsfactory.github.io/gdsfactory/notebooks/plugins/meep/002_gratings.html#grating-sparameters
the grating coupler should have around 5dB insertion loss, but tidy3d shows at least 10dB loss

**Comment by joamatab** [comment]
What's the definition of the `waist_radius` for the GaussianBeam?

https://docs.flexcompute.com/projects/tidy3d/en/latest/notebooks/GratingCoupler.html#Gaussian-beam-into-the-coupler

What would be the beam waist for a 10.4um Single mode fiber at 1550nm?

**Comment by lucas-flexcompute** [comment]
@joamatab The two links you cite have different simulations: Meep seems to be running in 2D and Tidy3D in 3D. If that is the case, you cannot compare the results. Simulating gratings in 2D is only useful for coarse adjustments, because the results are not valid for the 3D version. Even matching the 3D version with real data can be tricky, because minor imperfections in fabrication can lead to significant divergences in wavelength response.

As for the [Gaussian beam](https://en.wikipedia.org/wiki/Gaussian_beam), it should be a good initial approximation for the fundamental mode in SMF or small FMF with the waist positioned at the fiber facet (straight-cut) with a diameter close to the fiber's mode field diameter. If you want to simulate a lensed fiber, the waist should be positioned at the focal point with a radius defined by the beam diameter at the focus point (for all intents and purposes, a lensed fiber is actually generating a Gaussian beam close to its tip).

With all of that in mind, I'll see if I can match 3D simulations in Meep and Tidy3D and let you know of the results.

**Comment by joamatab** [comment]
Hi Lucas, 

I'm running 2d simulations in all cases so the mode overlaps should give similar results

**Comment by lucas-flexcompute** [comment]
I see! I looked only at the images and assumed it was 3D! Sorry.
Anyway, I'll keep looking to see if I spot any differences that should explain the divergence in results.

**Comment by joamatab** [comment]
Hi Lucas and Tyler,

These grating couplers should also show 5dB insertion loss at 1550nm 
https://gdsfactory.github.io/ubc/notebooks/11_sparameters_gratings.html

**Comment by tylerflex** [comment]
@joamatab can you provide a bit more information so we know how to begin looking into this? eg.
* You expect 5db based on what? another simulation? experiment?
* Have you done a resolution scan? or ensured that the simulation parameters are giving converged results or otherwise set up the same way as your other simulations?
* Maybe you can include some field monitors and run the notebook again so we can take a look at eg. the cross sectional field patterns?
These things might help us a bit in starting to look into this, but otherwise it's a bit hard to know where to start.

**Comment by lucas-flexcompute** [comment]
@joamatab Just to make sure: the simulation measures the fiber field inside the cladding material. That is the same in the Lumerical simulations, right? And are the experiments done with any index-matching medium to close the air gap between the fiber and the chip surface?

**Comment by tomflexcompute** [comment]
@joamatab It seems like when the simulation is in 2D, the normalization could be problematic since the source power is always 1W in Tidy3D. When you set `is_3d=True`, here is the result I got
![image](https://user-images.githubusercontent.com/116006359/212784888-154f6582-a039-4bd8-8318-37b85a0eb87e.png)
Does it look reasonable?

**Comment by joamatab** [comment]
Hi Lukas, the lumerical and meep sims do not have index matching 

Hi Tom, the power looks good but the center wavelength should be centered at 1550nm

**Comment by tylerflex** [comment]
@joamatab did this ever get resolved? Also, see the discussion in #664 , which could explain some discrepancy.

**Comment by joamatab** [comment]
Hi Tyler, it did not get resolved,

i think it's a bug and should be fixed :)

the recommended workaround of running it in 3D it's not really a good solution

**Comment by momchil-flex** [comment]
@joamatab the issue we discovered is that the Gaussian Beam normalization is slightly off for 2D simulations. In meep, is there an attempt of normalization at all? Or do you do a normalizing run with an empty simulation and use that to normalize the full simulation? If you are taking this approach, you could also do that for tidy3d for 2D simulations as a temporary solution. I'll look into fixing the bug, meanwhile.

**Comment by shashwat-sh** [comment]
@joamatab not sure if this is the root cause of your issue, but in the definition of `get_simulation_grating_coupler` [here](https://gdsfactory.github.io/gdsfactory/notebooks/plugins/tidy3d/00_tidy3d.html#get_simulation_grating_coupler), the simulation's `boundary_spec` should be defined as
```python
boundary_spec=td.BoundarySpec(
        x=td.Boundary.pml(),
        y=td.Boundary.periodic(),
        z=td.Boundary.pml(),
    )
```
i.e., a 2D simulation should have periodic boundaries in the direction where its size is 0. Please let us know if this helps.

**Comment by lucas-flexcompute** [comment]
@joamatab With the change that @shashwat-sh proposes, the simulation in 2D seems to match the 3D version (the peak efficiency, no the whole profile, of course), and it is similar to the incorrect 2D simulation apart from a normalization issue.

Do you want a PR to modify the default value for `boundary_spec` when `is_3d == False`? I've had to incorporate a few other minor changes because `plot_modes == True` was not working either.

3D:
![download](https://user-images.githubusercontent.com/119979961/220133240-1aeb2ca7-ef04-4a34-8e01-3cf44499dc91.png)

2D without periodic boundary in y:
![download](https://user-images.githubusercontent.com/119979961/220133391-85bde1cc-b318-4fec-99e2-270b7340b717.png)

2D with periodic boundary in y:
![download](https://user-images.githubusercontent.com/119979961/220133576-281f824f-c754-4924-ac47-c23483cfadb9.png)

[Source here](https://gist.github.com/lucas-flexcompute/a69078522ce93d4464fc5792bf73f7de)

**Comment by joamatab** [comment]
Yes, Lucas

PR would be great

**Comment by joamatab** [comment]
Hi Lucas,

For the 2D case, Im having some issues

![image](https://user-images.githubusercontent.com/4514346/220486203-6d9aca1b-50aa-4690-b84e-8b94f99caeb0.png)


See  https://github.com/gdsfactory/gdsfactory/pull/1322

**Comment by lucas-flexcompute** [comment]
It looks like the last changes increased the size of the ports (maybe also the simulation) in the z direction. The port is overlapping with the substrate and the "waveguide" mode is now localized in the substrate, not the waveguide.

I see that the simulation setup uses `box_thickness` and `z_margin` to set the size as
```python
sim_zsize = thickness_pml + box_thickness + wg_thickness + thickness_pml + 2 * zmargin
```
and the port size:
```python
size_z = wg_thickness + 2 * zmargin
```
Should we change the port size to be `box_thickness + wg_thickness + zmargin` and leave the waveguide off-center or remove `box_thickness` from the simulation size? The latter option might exclude the substrate from the simulation if `z_margin < box_thickness`, which is incorrect for grating simulations, so we'd have to increase `z_margin` if that's the case.

It seems to me that leaving the waveguide off-center work (for default arguments) and is more straightforward. What do you think?

BTW, the simulation cache must be invalidated after these changes. Is there a way to enforce it for the users?

**Comment by joamatab** [comment]
Thank you Lucas and Shashwat Sharma for the fix

https://github.com/lucas-flexcompute/gdsfactory/commit/894b77d5f0b01aefa55e213c8ced7684271a96ea

@shashwat-sh
