### ISSUE TITLE
upgrade to shapely>= 2.0.0

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#642]
How could we make tidy3d compatible with the latest version of shapely?

https://github.com/gdsfactory/gdsfactory/pull/996

**Comment by momchil-flex** [comment]
I've opened #643 that fixes this. There's only one change needed in the code.

However, when it comes to building it, shapely 2.0 failed to build on one of our workers that uses python 3.7. That is why I have kept the required version to 1.8.0 for python 3.7 and 2.0 for higher python. There were some weird issues where different patches of 1.8 would error for different python versions, which is why ideally I want to just have >= 2.0 eventually. Is this what you're planning for gdsfactory too?

**Comment by joamatab** [comment]
Hi Momchil,

we test gdsfactory plugins including tidy3d with python3.7 and python3.10
https://github.com/gdsfactory/gdsfactory/actions/runs/3840773093

how about we unpin shapely so each python version gets the latest shapely version?

**Comment by joamatab** [comment]
see the error of tidy3d with shapely 2.0.0 on python3.10

https://github.com/gdsfactory/gdsfactory/actions/runs/3871932000/jobs/6600214073

**Comment by momchil-flex** [comment]
Yeah, this is fixed in #643 , but we haven't merged this in yet as we want to make sure setting the version to 2.0 will not cause other issues. The shapely R tree which we are using in the mesher had some version issues, like it would produce an error on some versions of shapely and python...

@tylerflex if we're building a 1.8.2 patch maybe we could just merge the change to `mesher.py` from that PR. It just ensures that the mesher works with both shapely 1.x and 2.x.

**Comment by joamatab** [comment]
how about not pin the version? 

or if you switch to poetry you can specify 
pytest = "^2.0.0"

**Comment by momchil-flex** [comment]
We are working towards switching to poetry

**Comment by tylerflex** [comment]
@momchil-flex I'm fine with #643 going in 1.8.2. I'm a bit unsure about the shapely / python specifics but if that PR fixes things feel free to merge it into develop.

**Comment by tylerflex** [comment]
For reference: our poetry PR #624

**Comment by momchil-flex** [comment]
I'm reluctant to not pin the version for now since I've experienced issues on some combinations of python + shapely and want to avoid those. @joamatab if we are to push a patch (before we switch to poetry), would you rather the pinning stays with 1.8 as it is now, or 2.0?

**Comment by joamatab** [comment]
Pinning to the most current version would be best in my opinion 


Gdsfactory other plug-ins require shapely 2.0.0 or higher
