### ISSUE TITLE
_field_decay_warning is incorrectly triggered when symmetry is used

### ISSUE THREAD

**Issue by tomflexcompute** [flexcompute/tidy3d#644]
When the Simulation contains symmetry, _field_decay_warning will be triggered even though the field is zero at all boundaries. I suspect this is because the symmetry plane, instead of the real boundary of the mode solving box, is registered as the boundary by the ModeSolver. 

For example, here are the fields of 4 TE modes when symmetry (0,0,1) is used. Clearly the field is zero at boundaries.
<img width="321" alt="image" src="https://user-images.githubusercontent.com/116006359/210383887-471f8e82-79bb-431c-ae96-f42621d601b6.png">

However, the warning still shows up:
<img width="384" alt="image" src="https://user-images.githubusercontent.com/116006359/210384081-95769996-1340-4eed-9b46-434d5a8108bb.png">

**Comment by tylerflex** [comment]
Thanks @tomflexcompute, does seem like a bug. Maybe the approach to fix this is to check these `isel()` calls and ignore the `0` element in `plane_dims` if there is symmetry along that plane dimension? I'm not as familiar with the mode solver so maybee @weiliangjin2021 has some ideas.

**Comment by momchil-flex** [comment]
The fastest solution should be to just change to `mode_solver_data.symmetry_expanded_copy` [here](https://github.com/flexcompute/tidy3d/blob/82635156627951f022ac9eb1ab00743451f97c19/tidy3d/plugins/mode/mode_solver.py#L183) (or call `field_data.symmetry_expanded_copy` within the field decay warning method).

What Tyler is proposing may be a more efficient way to go about it though in case making the symmetry expanded copy has non-negligible overhead for large modes / many frequencies. I think instead of ignoring that dimension though, we should just double the right-side contribution and ignore the left-side contribution.
