### ISSUE TITLE
Move GDSTK to basic requirements for v1.9

### ISSUE THREAD

**Issue by zeyueN** [flexcompute/tidy3d#679]
https://github.com/flexcompute/tidy3d/blob/9859e8a96242abbd5feadc47cfa1f1aaa15a3b41/requirements/dev.txt#L11

So that we don't have to specify the dev extras. 🙏

**Comment by tylerflex** [comment]
Thanks @zeyueN , we added `gdstk` to `dev` requirements because it can be a bit more tricky to install compared to the other requirements and is only used in `PolySlab.from_gds` classmethod as far as I remember. But I agree it should probably be made available without having to install all of the dev requirements. 

@lucas-flexcompute what do you think? Is it safe to include `gdstk` as a basic requirement? or would it be better to separate it into its own requirement, eg. `pip install "tidy3d[gds]"`? I'm just trying to get a sense of whether my issue with installing `gdstk` will happen to other users. (As a reminder: I had a new computer and hadn't installed `cmake` yet). My concern is that users with less programming experience might run into this issue and not know how to resolve it.

**Comment by zeyueN** [comment]
An `[gds]` extra would be indeed the most convenient.

And yes it's tricky to install gdstk. It would be great if it had wheels built for more platforms, e.g. `manylinux2014`

**Comment by lucas-flexcompute** [comment]
Yes, sounds good to have it as an optional dependency, since it's only used in a single function.

**Comment by momchil-flex** [comment]
How about we provide both `tidy3d[gdspy]` and `tidy3d[gdstk]`, and internally, just handle both, prioritizing gdstk if present?

**Comment by lucas-flexcompute** [comment]
The only issue here is that the APIs are not 100% compatible, so we have to keep separate code paths depending on which library we find.

**Comment by tylerflex** [comment]
A few questions:
1. With the recent patch to gdstk do we still want to make gdstk an optional requirement? 
2. Do we want to support gdspy as a fallback? since it only comes up once I feel like having separate paths is not too bad to maintain for now. We could define two separate methods, like `PolySlab.from_gdspy()` and `PolySlab.from_gdstk()` and just do the switching in `PolySlab.from_gds()` based on what packages are imported? something like this ugly bit of code:
```py
@classmethod
def from_gds(cls, **kwargs):
    try:
         import gdstk
         return cls.from_gdstk(**kwargs)
    except ImportError:
        try:
            log.warning('could not import gdstk, trying gdspy')
            import gdstk
            return cls.from_gdspy(**kwargs)
        except ImportError:
            raise Tidy3DError("could not import gdstk or gdspy, not able to call from_gds...") from e
```

3. maybe we can just leave `gdspy` and `gdstk` out of our requirements entirely and ask the user to install them separately? or would this cause problems for our users? Guess it would be good to be able to specify compatible versions.

**Comment by lucas-flexcompute** [comment]
I like the idea of having gdspy as a fallback and leaving both as optional dependencies, since they are only used in those functions. I believe the 2 recent bug fixes in gdstk (0.9.36 and 0.9.37) will help alleviate a lot the installation issues some users were having, but still, in my opinion, the fewer dependencies, the better.

**Comment by momchil-flex** [comment]
@tylerflex let's add both `gdspy` and `gdstk` as optional modifiers to the installation. I think for now we can modify `from_gds` as you suggest, in the future we can think of a more extendable way of handling this if needed. Let's try to put this in `rc2`?

**Comment by tylerflex** [comment]
See this PR #683, think it warrants a bit more discussion on how I set it up but let me know what you think.

**Comment by momchil-flex** [comment]
In 1.9.0rc2, we have added [gdspy] and [gdstk] extras and support either package for gds import.
