### ISSUE TITLE
Refactor `smatrix`

### ISSUE THREAD

**Issue by tylerflex** [flexcompute/tidy3d#717]
The internals of `smatrix` tool are really clunky because of how Batch is organized (a batch uploads its jobs whenever it is initialized). We should consider refactoring it to use `run_async` instead so we can more cleanly perform the internals, otherwise it is impossible to understand what's going on currently.

To do
- [ ] refactor run to use `run_async`
- [ ] Get rid of unnecessary class methods once we can run_async instead of needing to initialize a batch.
- [ ] update element mappings and run_only to use `xr.DataArray` or a datastructure more similar to `SMatrixType`
- [ ] Fix docstrings to account for the fact that S_ij maps source j to monitor i (switched currently).
- [ ] Add utility function for element mappings of reciprocal device.

**Comment by tylerflex** [comment]
@lucas-flexcompute do you think the smatrix tool will even be relevant soon? is this worth the effort?

**Comment by lucas-flexcompute** [comment]
I think S matrix is very useful! I'm using it exclusively for simulation, because using ports is much easier than defining monitors/sources by hand. That said, I'm not sure the refactor is a priority, because it is perfectly functional right now and I don't see the refactor as a huge improvement in usability, it looks more like a "nice to have" thing.

**Comment by tylerflex** [comment]
ok that's good to know! I didn't remember if you were working on just replacing it or not. I'll keep this issue active then and just get into it when I have time
