### ISSUE TITLE
Group index computation from mode solver

### ISSUE THREAD

**Issue by momchil-flex** [flexcompute/tidy3d#819]
Would be helpful to add some in-build functions to compute and plot the group index.

I am not sure if there's anything more to it than taking a numerical derivative of the dispersion?

**Comment by lucas-flexcompute** [comment]
There is something already there in https://github.com/flexcompute/tidy3d/pull/743: https://github.com/flexcompute/tidy3d/blob/df4c5ce5aacbdac9c2b5ef7d36e2d2f5586fb370/tidy3d/plugins/waveguide/rectangular_dielectric.py#L650

The issue is that the numerical differentiation is sensitive to the grid changes without subpixel averaging. We also have to be careful with mode crossings, so all calculations (all required wavelengths for differentiation) have to be performed in a single run because of the mode sorting.

All that said, it should be pretty straightforward to port the code from the plugin to mode solver.
