### ISSUE TITLE
Avoid placing adjoint ModeSource-s for modes with very low amplitude in the forward simulation

### ISSUE THREAD

**Issue by momchil-flex** [flexcompute/tidy3d#820]
A common usage of a `ModeMonitor` in an adjoint optimization may be to e.g. define the objective function as the power in a target mode over the sum of power in all other modes. This makes the OF dependent on the amplitudes of all outgoing modes, and places one adjoint source for each of them. This can currently make things noticeably inefficient in the pre-processing, especially when the user has selected a large number of modes in the `mode_spec`. We could improve on that in the backend, but a simple improvement is also to not add sources that will have very small amplitude compared to other ones. For example, only add a source if the associated mode_amp is larger than some cutoff threshold times the largest mode_amp recorded. Or, probably better, set the cutoff based on the gradient vector.

**Comment by tylerflex** [comment]
Hm. A few comments:
1. Is this really high priority? are there users doing this currently? I have a lot of other features to add to adjoint plugin and want to prioritize appropriately.
2. Note that this could be done client-side by simply only adding the mode output to the objective if it's above a certain threshold (defined by the user). I feel a bit icky about setting an arbitrary cutoff that could affect accuracy.

**Comment by momchil-flex** [comment]
I put it as high priority because it should be a pretty small change compared to anything else, but you can re-arrange priorities as you wish. I think if the threshold is something like 1e-6 or 1e-7 such that we just exclude mode amplitudes close to numerical precision, it would have no effect on accuracy and will still eliminate many of the mode sources. Yeah technically the user could do it in their OF but no user is actually going to do it...

**Comment by tylerflex** [comment]
We can just use the Size field if it's a small change I suppose.

Anyway, I just have a few reservations about this / need to think about it some more. Thinking out loud, what I'm concerned about is whether cutting out an adjoint source could have a big affect on the accuracy of the gradient. I'd like to rule out possible edge cases. A few notes
* We can't cut off w.r.t. the gradient vector because we don't know the gradient vector before running the adjoint source. Only way to include this gradient info would be to pass it explicitly into the JaxSimulation, which seems quite tedious and still requires the user to do something on their side.
* A source with a small amplitude compared to the other ones might still have a large effect on the objective function / gradient in some context. I'm trying to rule out any edge cases, but for example, if the waveguides with large amplitude are not connected to the design region, but have high amplitude, it would throw things off. I'll try to draw a situation I have in mind.
```
                  ================== -> 1
                //
-> ======{ design region }====== -> 2
```

if the design region is very reflective, amp 2 could be much smaller than amp 1. It might satisfy criteria to filter it out in fact. But we can see clearly that output 1 has no affect on the gradient w.r.t. the design region because any adjoint sourced waves from 1 will not propagate through it.

So I feel like these kinds of edge cases should be considered before we implement this. Let me know if you have thoughts.

**Comment by tylerflex** [comment]
> I guess we don't have established guidelines about who should be setting these fields, it could be that the reporter does and then assignee modifies if needed, or it could be that reporter just adds it to the project but leaves all fields (including status?) blank. I'm fine with the latter.

my point is just that the size and priority can be decoupled. If something is not that urgent but small, we can just assign it as such instead of bumping priority on account of the small changes. But it's not important

**Comment by tylerflex** [comment]
Notes for later.
```pt
max_amp = np.max(np.abs(amps))
cutoff = f * max_amp
for amp in amps:
    if abs(amp) < cutoff:
         continue
```
`f` should be 1e-7 or 1e-8
