### ISSUE TITLE
simulation cache

### ISSUE THREAD

**Issue by joamatab** [flexcompute/tidy3d#936]
in gdsfactory we have a cache based on hashing the JSON file for simulation

I think implementing a cache so simulations previously computed to not need to run again would be great

 (you can take a look at gdsfactory/simulation/gtidy3d/get_results.py)

**Comment by Jan-David-Black** [comment]
It would also be great if such system also worked with the adjoint plugins :)

**Comment by Jan-David-Black** [comment]
@joamatab, @tylerflex,
I prepared a first draft how such a cache could integrated with tidy on the client side. So far It still uses a dict instead of propper Pydantic objects, and it also still has some nasty `print` debug statements. So some cleaning up still needed. https://github.com/Jan-David-Black/tidy3d/blob/patch-2/tidy3d/web/sim_cache.py
I am slightly abusing the s3 storage for saving the sim_cache.json
maybe an API endpoint for that would be usefull. However, that is out of my control...

**Comment by momchil-flex** [comment]
Thanks @Jan-David-Black!

For future reference when we get to working on that here's some considerations we need to make sure are worked out fine:
- This could be a pretty useful feature for debugging, but also we need to make sure we have a way to turn it off for other types of debugging (when the solver has changed).
- We saw at some point that hashing a simulation can take very long when there are e.g. many many structures (e.g. metalens). We need to either make sure that it's fast enough, or turn it off in such cases.
- We may want to hash not just the simulation but any extra fields that go into the web functions, like the new `simulationType` that's used in server-side adjoint.

**Comment by Jan-David-Black** [comment]
1. I wrote it so that you can set force to True (in `web.upload`) to ignore previously cached simulations. One would just have to propagate that to other functions using `upload` (e.g. `run`). Alternatively one could just clear the `sim_cache` by `tidy3d.web.sim_cache.upload_sim_cache({})`

2. We should consider adding a field to SimulationTask with which one can disable jsonifying the simulation, so that it can also be ignored while `build_sim_cache`, which goes through all simulations currently not recorded in the cache. Alternatively one could provide a manually generated cache key.

3. Absolutely. Should a Simulation object contain the simulation type as a field? Maybe that would be reasonable too?

**Comment by tylerflex** [comment]
This is great! Thanks @Jan-David-Black 

In general, we try to keep some separation between the raw component specs (eg. `Simulation`) and the `web` functions and objects. The components / specs are completely agnostic to the web functions wrapping them and thus we can develop the components without worrying too much about complex interdependencies there. So this is the main reasoning behind not putting the `simulation_type` field inside of `Simulation` directly, but instead keeping it as a `kwarg` to the `upload` function. For now can we work with that? a greater refactoring of `web` might come in several months but this is the approach we have for now.

In the same line of thinking, we have the "pure" `SimulationTask` and the web functions that wrap this for the user, but also other convenience things like `Job` and `Batch` of `containers.py` that provide even higher level interfaces for managing simulations. My thinking is that if we can keep the caching similarly separated, it might help keep things organized down the line. I guess to me this suggests maybe not adding fields to `SimulationTask` directly, but just having a way to manually supply the hash key could be useful.

Can you provide what might be the API changes required for using the sim_cache? Seems like basically some ways to manipulate the cache through `tidy3d.web.sim_cache` namespace but then also some extra kwargs to `upload` (and the functions that depend on it?)

If we were to provide an API to our s3 storage, what would you suggest? I can relay things to the people working on that and we can try to come up with something. I think it would simplify things internally as well. Curious to hear your thoughts on that. 

Thanks!

**Comment by Jan-David-Black** [comment]
Ok, some questions for clarification: What is `simulation_type` actually about? How is it used in server side adjoint? to me it seems like a fundamental property of the simulation, but you guys seam convinced otherwise. Including `kwargs` does complicate things a bit, but should still be manageable. 

> In the same line of thinking, we have the "pure" SimulationTask and the web functions that wrap this for the user, but also other convenience things like Job and Batch of containers.py that provide even higher level interfaces for managing simulations. My thinking is that if we can keep the caching similarly separated, it might help keep things organized down the line. I guess to me this suggests maybe not adding fields to SimulationTask directly, but just having a way to manually supply the hash key could be useful.

Sounds good to keep concerns separated. Ma

**Comment by tylerflex** [comment]
> Ok, some questions for clarification: What is simulation_type actually about? How is it used in server side adjoint?

The `simulation_type` basically tells our backend how to treat the simulation. For example, it could be a regular simulation, forward adjoint simulation (which we cache some of the results of server-side), or an adjoint simulation. It was introduced with the server side adjoint processing because we required some way to distinguish these three simulation processing pipelines.

> to me it seems like a fundamental property of the simulation, but you guys seam convinced otherwise. Including kwargs does complicate things a bit, but should still be manageable.

It completely is a fundamental property of the simulation, however, there are other fields (like the task_name, folder_name, etc) that we also pass to `web.run()` that could similarly be considered properties of the simulation. While we could lump everything into the `Simulation` subclass, it seemed in some instances to make more sense to pass these as kwargs to the run function. For example, maybe I want to run the same `Simulation` with different task names without copying the whole thing and changing that one field. So I think your intuition is spot on, but we made a decision at some point to pass this simulation_type as a kwarg because it made sense at the time and fit better with our existing pipeline. Maybe in the future this could change but in the spirit of minimizing work and not breaking backwards compatibility, we will probably hold off for a while.

> Sounds good to keep concerns separated. I see two difficulties:

> we'll need to make sure it integrates well with all other abstractions (Jobs/Batches)

Yea this will require a bit of integration work, but it's relatively minor, we will just need to pass the right kwargs around. In this case, we could just add the custom hash value into the `Job._upload_fields` class [attribute](https://github.com/flexcompute/tidy3d/blob/develop/tidy3d/web/container.py#L79-L87) and it would probably just work. 

> When providing a custom hash we should probably add a prefix or similar to avoid collisions. (I can hardly imagine a case, in which you would want a cachehit between a manually provided hash and an autogenerated one)

Yea sounds totally reasonable to me.

> One architectural decision that needs to be taken is ...

I think I'll leave this to @momchil-flex and @lei-flex . maybe you guys have thoughts on the cache implementation?

Thanks!

**Comment by tylerflex** [comment]
Hey @jan-david-fischbach just stopping by and wondering if there were any updates on this?

**Comment by jan-david-fischbach** [comment]
Hi @tylerflex,
I haven't been putting in any more time, as I think the architectural decision needs to be taken first. Especially when it comes to endpoints on your end, I have no Idea, what is (if at all) in the making. If you like we can also set a date to discuss in person?

**Comment by tylerflex** [comment]
That's ok, just wanted to check since we were thinking of starting working on a caching feature. Might be easiest for us to handle it ourselves since it might require server-side work.  Once that is done, it should be possible to modify the gdsfactoy caching to use our feature.

**Comment by joamatab** [comment]
any updates on this?

**Comment by tylerflex** [comment]
I believe we're in the process of implementing something on our end, but am not so sure of the details. My impression is that it will work by keeping a cache server side and will just return data if a simulation spec has already been run. With an option to turn this off in the `web` functions.  Will keep you posted though!

**Comment by lei-flex** [comment]
There are 4 scenarios we need to consider:1. Python single task submit 2. Web single task submit 3. Python sweep task submit 4. Web sweep task submit And each of them could has their own workflow due to difference user interaction between python and web uiSent from my iPhoneOn Nov 20, 2023, at 1:09 PM, Tyler Hughes ***@***.***> wrote:﻿
I believe we're in the process of implementing something on our end, but am not so sure of the details. My impression is that it will work by keeping a cache server side and will just return data if a simulation spec has already been run. With an option to turn this off in the web functions.  Will keep you posted though!

**Comment by momchil-flex** [comment]
This has been implemented and is now on by default for all tidy3d versions @jan-david-fischbach @joamatab ! Give it a try!

Currently you can only disable it from your web client account page. In the future we will also support disabling it programatically.
