### ISSUE TITLE
Make warnings more noticeable or more strongly enforced

### ISSUE THREAD

**Issue by momchil-flex** [flexcompute/tidy3d#978]
**Is your feature request related to a problem? Please describe.**
We keep hitting issues like diverged simulations that could have been avoided if users would have heeded some of our automated warnings.

**Describe the solution you'd like**
It would be nice if we can make the warnings "stronger". One option is to have e.g. `allow_warning=False` flag in the `upload` or `run` function, and have it error if the simulation produces any warnings and it is not explicitly set to `True`. Would be useful if we can store a list of warnings in the simulation so we don't have to re-validate it.

**Describe alternatives you've considered**
Other options include asking the user interactively if they want to run it, but @xin-flex pointed out that we used to have issues with prompts  when we were using them for user name / password on different platforms and IDEs. Another option is to just make our warnings more visible by e.g. using the python `warnings` package (they're highlighed in red, an won't be turned off by our logging config level...) Or do this for the important ones at least?

**Comment by lucas-flexcompute** [comment]
I'm not sure I like the idea of throwing warnings a second time if the user already ignored it. I'm more inclined to use the warnings module and maybe issue the warning in the logger automatically, so, whenever we use `log.warning` we call `warnings.warn`. It can be added [here](https://github.com/flexcompute/tidy3d/blob/pre/2.3/tidy3d/log.py#L225) to comply with the current logger functionality. As it stands, warnings would be shown twice, but I guess in this case we can change our default logging level to "ERROR".

That said, whatever the solution, maybe we should think i little more carefully on the problem: the user ignoring the warning (that is already there). Maybe we're issuing too many (unnecessary) warnings and the user becomes used to ignoring them (I can tell this is my personal experience at least). For example, the warning about no sources in the simulation is one that constantly makes me turn off all warnings. What I'm saying is that we should turn more warnings into INFO, if they are not really dangerous, and issue warnings when they really matter (simulation divergence = possible loss of many credits). We could also have a separate category: CRITICAL_WARNING between WARNING and ERROR, which could be configured to optionally raise an error (true by default).

One advantage we already have in 2.3 is the new log filtering, which should at least decrease the amount of warnings printed at once.

**Comment by momchil-flex** [comment]
I think all of those are good points, we could improve significantly before forcing the user to have to explicitly allow a simulation with warnings to run. Would be great to get some of those in 2.4.

**Comment by lucas-flexcompute** [comment]
I can definitely have these changes in place by 2.4, but let's wait for @tylerflex's input before I make any changes. He might have other suggestions.

**Comment by tylerflex** [comment]
Yea this is a problem and I agree that the problem is largely two-fold:
1. Warnings are not really formatted as "loudly" as they could be. I think it makes sense to use warnings module. It would be best if we dont duplicate the warnings though. Maybe we can suppress our native log.warning() output in STDOUT and let the warnings module handle the output? setting default logging level to ERROR seems like a decent workaround but kind of defeats the purpose because then how do we suppress warnings if we want to? (would need to mess with warnings module?)
2. Maybe we either need to downgrade non-essential warnings to INFO or create two different WARNING / CRITICAL_WARNING levels. The "no sources" warning and the "override structures"  warnings come to mind as potentials for downgrade, as well as the adjoint warnings about accuracy with overlapping gradients (often users won't care about gradients w.r.t. these overlapping areas).

I'm not really sure of the best approach forward, maybe one approach is to reserve INFO for these non-critical, usability "hints" and so a user could set logging level to INFO if they wanted more detailed guidance about setting up a simulation properly, but reserve WARNING for critical warnings (users should not ignore). Everything else that's not critical at all (current INFO) could be moved to DEBUG? Like the version printing?

**Comment by tylerflex** [comment]
note, possible duplicate with #813, or at least, once this is resolved we can close that issue.

**Comment by lucas-flexcompute** [comment]
Although I like the warnings module, it will be another setting for the user to configure (and maybe more difficult to users not used to python, because it involves configure a separate module).

One thin we can try instead is to use the markup provided by `rich.Console` to increase our warning visibility, for example printing in red/bold text. It might not work for all terminal types, but should be okay within Jupyter and any modern terminals. Here's a quick example on JupyterLab and my terminal (with true color support):

![20230703-080249](https://github.com/flexcompute/tidy3d/assets/119979961/fba534e4-5c39-4fba-b8dd-146038ae9df9)

![20230703-080214](https://github.com/flexcompute/tidy3d/assets/119979961/45d430ab-6e23-432f-b17e-b02ddac90b43)

**Comment by tylerflex** [comment]
That seems like a pretty good solution. Maybe we can try that for now?
